# name of the conda environment
name: rna-report-test

#the paths that conda takes a look for packages. 
#avoid using anaconda as we have experienced issues with it
channels:
        - conda-forge
        - bioconda
        - r
        - plotly
        - defaults

#install following packages in the conda environment
dependencies:
        - libiconv
        - r-tidyverse
        - bioconductor-edger
        - r-rapportools
        - r-optparse
        - r-openxlsx
        - r-readr
        - r-tidyverse
        - r-dplyr
        - r-tidyr
        - r-rlang
        - r-dt
        - r-kableextra
        - r-matrixstats
        - r-knitr
        - r-plotly=4.9.0
        - plotly-orca
        - r-ggplot2 
        - r-ggforce
        - r-pdftools
        - r-png
        - r-htmltools
        - r-htmlwidgets
        - r-devtools
        - bioconductor-ensdb.hsapiens.v75
        - bioconductor-ensdb.hsapiens.v86 
        - bioconductor-bsgenome.hsapiens.ucsc.hg19  
        - bioconductor-bsgenome.hsapiens.ucsc.hg38       
